### ISSUE TITLE
php处理半透明图片有损，java版不能处理position center

### ISSUE THREAD

**Issue by kltk** [shepherdwind/joycss#36]
虽然影响不是很大
position center 应该是类似网站上提到的不能正确定位的情况
joycss:Error!! 拼图操作失败:Error Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
        at sun.awt.image.ByteInterleavedRaster.setDataElements(Unknown Source)
        at java.awt.image.BufferedImage.setRGB(Unknown Source)
        at org.joycss.ImageBuilder.drawImage(ImageBuilder.java:121)
        at org.joycss.ImageBuilder.buidImage(ImageBuilder.java:89)
        at org.joycss.ImageBuilder.main(ImageBuilder.java:43) +0ms

**Comment by shepherdwind** [comment]
居中定位确实不好处理，java跑错的情况，你可以把你的css和图片，打包发给我么？邮箱eward.song [at] gmail.com我这边试下看看问题出在哪里。

php半透明在png24的图片也有损，还是只是png8有损啊，如果是png8，应该是正常的，png24就有问题了。

**Comment by kltk** [comment]
png24，量不大，在半透明的边缘部分，代码我精简了下发给你了
